# Generated by Django 4.1.7 on 2024-04-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Video', 'Audio')], default='Video', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('x_frame_size', models.FloatField()),
                ('y_frame_size', models.FloatField()),
                ('douban_url', models.URLField(blank=True, null=True)),
                ('imdb_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('content', models.TextField()),
                ('duration', models.FloatField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frameworld.entry')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
                ('replies', models.TextField(blank=True)),
                ('popularity', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frameworld.entry')),
            ],
        ),
        migrations.CreateModel(
            name='FrameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('content', models.TextField()),
                ('duration', models.FloatField()),
                ('popularity', models.IntegerField()),
                ('x_position', models.CharField(max_length=10)),
                ('y_position', models.CharField(max_length=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frameworld.entry')),
            ],
        ),
    ]
