# Generated by Django 4.1.7 on 2024-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framecomment',
            name='duration',
        ),
        migrations.AddField(
            model_name='framecomment',
            name='replies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalcomment',
            name='replies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
