# Generated by Django 4.1.7 on 2024-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworld', '0002_remove_framecomment_duration_framecomment_replies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framecomment',
            name='x_position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='framecomment',
            name='y_position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
