# Generated by Django 4.1.7 on 2024-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworld', '0004_framecomment_user_globalcomment_user_subtitle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcomment',
            name='parentID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
