# Generated by Django 4.1.7 on 2024-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworld', '0011_entry_imdb_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='douban_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
